<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ARKON AI</title><link rel="stylesheet" href="./styles.css"></head><body>
<header><div class="brand"><div class="logo">A</div><div><h1>ARKON AI</h1><small>Institutional Market Intelligence</small></div></div><div class="status"><span></span><div><small>مزود البيانات</small><b id="provider">...</b></div></div></header>
<main><section class="summary"><div class="metric"><small>أفضل فرصة</small><b id="best">—</b></div><div class="metric"><small>فرص شراء</small><b id="buyCount">0</b></div><div class="metric"><small>فرص مراقبة</small><b id="watchCount">0</b></div><div class="metric"><small>آخر تحديث</small><b id="updated">—</b></div></section>
<section class="grid top"><article class="card decision"><div class="head"><div><small>ARKON AI DECISION</small><h2 id="decision">اختر سهمًا</h2></div><div id="quality" class="ring">—</div></div><div class="ticker"><div><strong id="symbol">—</strong><span id="price">—</span></div><em id="change">—</em></div><div id="reasons"></div></article>
<article class="card"><small>قوة الاتجاه</small><div class="big"><b id="trend">—</b><span id="trendText">—</span></div><div class="bar"><i id="trendBar"></i></div><small>الزخم، الحجم النسبي، واتجاه الحركة.</small></article>
<article class="card"><small>تمركز السيولة</small><div class="big"><b id="liquidity">—</b><span>Liquidity Score</span></div><div class="zones"><div><small>Put Wall</small><b id="putWall">—</b></div><div><small>المغناطيس</small><b id="magnet">—</b></div><div><small>Call Wall</small><b id="callWall">—</b></div></div></article></section>
<section class="grid scores"><div class="metric"><small>Institutional Score</small><b id="inst">—</b></div><div class="metric"><small>Risk Score</small><b id="risk">—</b></div><div class="metric"><small>Call Volume</small><b id="callVol">—</b></div><div class="metric"><small>Put Volume</small><b id="putVol">—</b></div></section>
<section class="grid content"><article class="card scanner"><div class="head"><div><small>OPPORTUNITY SCANNER</small><h2>فرص السوق</h2></div><button id="refresh">تحديث</button></div><div class="table-wrap"><table><thead><tr><th>السهم</th><th>القرار</th><th>الاتجاه</th><th>السيولة</th><th>المؤسسات</th><th>المخاطر</th><th>الجودة</th></tr></thead><tbody id="rows"></tbody></table></div></article>
<article class="card"><small>NO TRADE FILTER</small><h2>موانع الدخول</h2><div id="blocks"></div><hr><small>خطة الصفقة</small><div class="plan"><div><small>الدخول</small><b id="entry">—</b></div><div><small>الوقف</small><b id="stop">—</b></div><div><small>الهدف الأول</small><b id="t1">—</b></div><div><small>الهدف الثاني</small><b id="t2">—</b></div></div></article></section>
<p class="note">النظام تحليلي واحتمالي ولا يضمن نجاح الصفقات. لا ينفذ أوامر تلقائيًا.</p></main><div id="toast"></div><script src="./app.js"></script></body></html>